In [ ]:
import pandas as pd

file_path = "..dataset/train/train_source1.tsv"

df = pd.read_csv(file_path, sep="\t")

print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 5 records:")
display(df.head())

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

FileNotFoundError: [Errno 2] No such file or directory: '..dataset/train/train_source1.tsv'

In [4]:
import os

project_path = os.path.expanduser(
    "~/Downloads/Business Entity Resolution"
)

for root, dirs, files in os.walk(project_path):
    if "train_source1.tsv" in files:
        print("Dataset found:", os.path.join(root, "train_source1.tsv"))
        break

Dataset found: /Users/aiwinthomas/Downloads/Business Entity Resolution/dataset/train/train_source1.tsv

In [5]:
import pandas as pd

file_path = "/Users/aiwinthomas/Downloads/Business Entity Resolution/dataset/train/train_source1.tsv"

df = pd.read_csv(file_path, sep="\t", nrows=5)

display(df)

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

In [6]:
print("Dataset shape:", df.shape)
print("Columns:", df.columns.tolist())

Dataset shape: (5, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

In [7]:
df = pd.read_csv(file_path, sep="\t")

print("Dataset shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Dataset shape: (2206821, 4)

Missing values:
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

Duplicate rows: 0

In [8]:
print("First 10 records:")
display(df.head(10))

print("\nRandom 10 records:")
display(df.sample(10, random_state=42))

print("\nData types:")
print(df.dtypes)

print("\nUnique countries:")
print("Number of countries:", df["country"].nunique())
print(df["country"].value_counts().head(20))

First 10 records:

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India
5,S1-851869949,Custom Wealth Services LLC,"OH, Columbus, 5559 Orville Avenue",US
6,S1-785847572,Consulting Nyasa Nursing Private Limited,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",India
7,S1-27541239,Nexus Anchor Rain,"1111 Church Street, Unit 2007, Nashville, TN",US
8,S1-629417405,Moore Bitwise Inc,"337 Oakland Avenue, Michigan City, IN",US
9,S1-22305073,Dermatology Green Medicine,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",US

Random 10 records:

,entity_id,business_name,business_address,country
2195840,S1-53356671,Pediatric Medicine PLLC,"4850 20, Otisco, NY",US
1487051,S1-320151505,Fetech National Twin,"19034 Woodburn Road, Woodburn, IN",US
1878277,S1-938947364,General Design Innovations LLC,"7241 Osage Avenue, Mesa, AZ",US
993966,S1-195839862,Construction Ideaz Papers Private Limited,"Building No.4/606, Prabhul Cottage Karimbalur,...",India
565428,S1-655046555,Penaloza and Bittle First Inc.,"4255 Charleswood Avenue, Memphis, TN",US
1645753,S1-758070915,National Investments LLC,"1641 Virginia Lane, Hueytown, AL",US
1165724,S1-169338169,Reus Idaho Company,"Sanford, ME, 31 Guillemette Street",US
363842,S1-796421498,Creative Projects Limited,"12Thfloor, C, 1204, Roya Oasis, Jankalyan Naga...",India
962445,S1-802535179,Goar Stone LLC,"2105 Wood Ridge Cove, Cedar Park, TX",US
964820,S1-97176033,Lakshmi Consultants Private Limited,"A-301, New Sai Dham Chsl, Ramdev Park Road, Th...",India

Data types:
entity_id           str
business_name       str
business_address    str
country             str
dtype: object

Unique countries:
Number of countries: 2
country
US       1323633
India     883188
Name: count, dtype: int64

In [9]:
print("Total records:", len(df))
print("Unique entity IDs:", df["entity_id"].nunique())
print("Duplicate entity IDs:", df["entity_id"].duplicated().sum())

Total records: 2206821
Unique entity IDs: 2206821
Duplicate entity IDs: 0

In [10]:
print(df["country"].value_counts())

country
US       1323633
India     883188
Name: count, dtype: int64

In [11]:
from pathlib import Path
import pandas as pd

base = Path(
    "/Users/aiwinthomas/Downloads/Business Entity Resolution"
)

files = [
    "dataset/train/train_source1.tsv",
    "dataset/train/train_source2.tsv",
    "dataset/train/train_source3.tsv",
    "dataset/train/train_ground_truth.tsv",
]

for file in files:
    path = base / file

    sample = pd.read_csv(path, sep="\t", nrows=5)

    print(f"\n--- {path.name} ---")
    print("Columns:", sample.columns.tolist())

    # Count records without loading the full file into memory
    with open(path, "rb") as f:
        row_count = sum(1 for _ in f) - 1

    print("Data rows:", row_count)
    display(sample)

--- train_source1.tsv ---
Columns: ['entity_id', 'business_name', 'business_address', 'country']
Data rows: 2206821

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

--- train_source2.tsv ---
Columns: ['entity_id', 'business_name', 'business_address', 'country']
Data rows: 5034616

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

--- train_source3.tsv ---
Columns: ['entity_id', 'business_name', 'business_address', 'country']
Data rows: 5285603

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

--- train_ground_truth.tsv ---
Columns: ['source1_entity_id', 'matched_entity_ids']
Data rows: 2206821

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [12]:
import pandas as pd
from collections import Counter

ground_truth_path = (
    "/Users/aiwinthomas/Downloads/"
    "Business Entity Resolution/dataset/train/"
    "train_ground_truth.tsv"
)

match_counts = Counter()
source_counts = Counter()
total_rows = 0

for chunk in pd.read_csv(
    ground_truth_path,
    sep="\t",
    usecols=["source1_entity_id", "matched_entity_ids"],
    dtype=str,
    chunksize=100_000
):
    total_rows += len(chunk)

    for matched_ids in chunk["matched_entity_ids"].dropna():
        ids = [
            entity_id.strip()
            for entity_id in matched_ids.split(",")
            if entity_id.strip()
        ]

        match_counts[len(ids)] += 1

        for entity_id in ids:
            if entity_id.startswith("S2-"):
                source_counts["Source 2"] += 1
            elif entity_id.startswith("S3-"):
                source_counts["Source 3"] += 1
            else:
                source_counts["Other prefixes"] += 1

print("Ground-truth rows:", total_rows)

print("\nNumber of matched IDs per Source 1 record:")
for count, records in sorted(match_counts.items()):
    print(f"{count} matches: {records:,} records")

print("\nTotal matching IDs by source:")
print(source_counts)

Ground-truth rows: 2206821

Number of matched IDs per Source 1 record:
1 matches: 119,157 records
2 matches: 375,212 records
3 matches: 530,841 records
4 matches: 484,115 records
5 matches: 321,957 records
6 matches: 164,868 records
7 matches: 63,968 records
8 matches: 18,680 records
9 matches: 4,205 records
10 matches: 534 records
11 matches: 37 records

Total matching IDs by source:
Counter({'Source 3': 3944746, 'Source 2': 3693619})

In [13]:
import pandas as pd

base_path = (
    "/Users/aiwinthomas/Downloads/"
    "Business Entity Resolution/dataset/train/"
)

files = {
    "Source 1": "train_source1.tsv",
    "Source 2": "train_source2.tsv",
    "Source 3": "train_source3.tsv",
}

for source, filename in files.items():
    df = pd.read_csv(
        base_path + filename,
        sep="\t",
        usecols=["country"],
        dtype=str
    )

    print(f"\n{source}")
    print(df["country"].value_counts(dropna=False))

Source 1
country
US       1323633
India     883188
Name: count, dtype: int64

Source 2
country
US       3016817
India    2017799
Name: count, dtype: int64

Source 3
country
US       3170056
India    2115547
Name: count, dtype: int64

In [14]:
import pandas as pd

ground_truth_path = (
    "/Users/aiwinthomas/Downloads/"
    "Business Entity Resolution/dataset/train/"
    "train_ground_truth.tsv"
)

gt = pd.read_csv(
    ground_truth_path,
    sep="\t",
    dtype=str,
    nrows=10
)

print(gt.to_string(index=False))

source1_entity_id                                                            matched_entity_ids
        S1-965667               S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364
      S1-55344266                           S2-249013014,S2-197070651,S3-478195123,S3-384364074
     S1-343815751                                        S2-790675320,S2-479876582,S3-878454467
     S1-656753428                                         S2-153058913,S2-24659151,S3-679606215
     S1-102811957 S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785
      S1-18727616                           S2-755677256,S3-187831601,S3-641489370,S3-476250621
     S1-318373630                                                     S2-660036492,S3-804600254
      S1-86989137                                                     S3-274817120,S3-312496301
      S1-29845983                                                     S2-648035184,S3-588502663
     S1-789009573                                         S2-383871912,S3-74481402,S3-576451439

In [15]:
import pandas as pd
import re

base_path = (
    "/Users/aiwinthomas/Downloads/"
    "Business Entity Resolution/dataset/train/"
)

def normalize_name(name):
    if pd.isna(name):
        return ""

    name = str(name).lower()
    name = re.sub(r"[^\w\s]", " ", name)
    name = re.sub(r"\s+", " ", name).strip()

    return name

# Load a small sample from each source
s1 = pd.read_csv(
    base_path + "train_source1.tsv",
    sep="\t",
    dtype=str,
    nrows=5000
)

s2 = pd.read_csv(
    base_path + "train_source2.tsv",
    sep="\t",
    dtype=str,
    nrows=5000
)

s3 = pd.read_csv(
    base_path + "train_source3.tsv",
    sep="\t",
    dtype=str,
    nrows=5000
)

# Normalize business names
for df in [s1, s2, s3]:
    df["name_normalized"] = df["business_name"].apply(
        normalize_name
    )

    df["name_prefix"] = df["name_normalized"].str[:4]

print("Source 1 sample:", len(s1))
print("Source 2 sample:", len(s2))
print("Source 3 sample:", len(s3))

Source 1 sample: 5000
Source 2 sample: 5000
Source 3 sample: 5000

In [16]:
# Keep records with usable blocking keys
s1_valid = s1[
    s1["country"].notna()
    & s1["name_prefix"].ne("")
]

s2_valid = s2[
    s2["country"].notna()
    & s2["name_prefix"].ne("")
]

s3_valid = s3[
    s3["country"].notna()
    & s3["name_prefix"].ne("")
]

# Generate Source 1 -> Source 2 candidates
candidates_s2 = s1_valid.merge(
    s2_valid,
    on=["country", "name_prefix"],
    suffixes=("_s1", "_s2")
)

# Generate Source 1 -> Source 3 candidates
candidates_s3 = s1_valid.merge(
    s3_valid,
    on=["country", "name_prefix"],
    suffixes=("_s1", "_s3")
)

print("Source 1 -> Source 2 candidates:", len(candidates_s2))
print("Source 1 -> Source 3 candidates:", len(candidates_s3))
print(
    "Total candidates:",
    len(candidates_s2) + len(candidates_s3)
)

Source 1 -> Source 2 candidates: 16329
Source 1 -> Source 3 candidates: 17394
Total candidates: 33723

In [17]:
# Load ground truth for the Source 1 sample
gt = pd.read_csv(
    base_path + "train_ground_truth.tsv",
    sep="\t",
    dtype=str
)

sample_s1_ids = set(s1["entity_id"])

gt_sample = gt[
    gt["source1_entity_id"].isin(sample_s1_ids)
].copy()

# Convert candidate pairs into sets of ID pairs
candidate_pairs_s2 = set(
    zip(
        candidates_s2["entity_id_s1"],
        candidates_s2["entity_id_s2"]
    )
)

candidate_pairs_s3 = set(
    zip(
        candidates_s3["entity_id_s1"],
        candidates_s3["entity_id_s3"]
    )
)

candidate_pairs = candidate_pairs_s2 | candidate_pairs_s3

# Count true matches found among the candidates
true_matches = 0
found_matches = 0

for _, row in gt_sample.iterrows():
    s1_id = row["source1_entity_id"]

    matched_ids = [
        x.strip()
        for x in row["matched_entity_ids"].split(",")
        if x.strip()
    ]

    for matched_id in matched_ids:
        true_matches += 1

        if (s1_id, matched_id) in candidate_pairs:
            found_matches += 1

print("Ground-truth matches for sampled Source 1 records:", true_matches)
print("Matches found by blocking:", found_matches)

if true_matches:
    print(
        "Candidate recall:",
        round(found_matches / true_matches * 100, 2),
        "%"
    )

AttributeError: 'float' object has no attribute 'split'

In [18]:
true_matches = 0
found_matches = 0
missing_ground_truth = 0

for _, row in gt_sample.iterrows():
    s1_id = row["source1_entity_id"]
    matched_value = row["matched_entity_ids"]

    # Handle missing ground-truth values
    if pd.isna(matched_value) or not str(matched_value).strip():
        missing_ground_truth += 1
        continue

    matched_ids = [
        x.strip()
        for x in str(matched_value).split(",")
        if x.strip()
    ]

    for matched_id in matched_ids:
        true_matches += 1

        if (s1_id, matched_id) in candidate_pairs:
            found_matches += 1

print("Ground-truth matches:", true_matches)
print("Matches found by blocking:", found_matches)
print("Rows with missing ground truth:", missing_ground_truth)

if true_matches > 0:
    print(
        "Candidate recall:",
        round(found_matches / true_matches * 100, 2),
        "%"
    )

Ground-truth matches: 17362
Matches found by blocking: 18
Rows with missing ground truth: 289
Candidate recall: 0.1 %

In [19]:
# IDs present in our samples
s2_sample_ids = set(s2["entity_id"])
s3_sample_ids = set(s3["entity_id"])

matches_in_sample = 0
matches_outside_sample = 0

for _, row in gt_sample.iterrows():
    matched_value = row["matched_entity_ids"]

    if pd.isna(matched_value):
        continue

    s1_id = row["source1_entity_id"]

    for matched_id in str(matched_value).split(","):
        matched_id = matched_id.strip()

        if not matched_id:
            continue

        if matched_id.startswith("S2-"):
            exists = matched_id in s2_sample_ids
        elif matched_id.startswith("S3-"):
            exists = matched_id in s3_sample_ids
        else:
            continue

        if exists:
            matches_in_sample += 1
        else:
            matches_outside_sample += 1

print("True matches present in the source samples:", matches_in_sample)
print("True matches outside the source samples:", matches_outside_sample)

True matches present in the source samples: 24
True matches outside the source samples: 17338

In [20]:
# Select 10 Source 1 records that have ground-truth matches
test_gt = gt_sample[
    gt_sample["matched_entity_ids"].notna()
].head(10)

# Collect their true matching IDs
needed_s2_ids = set()
needed_s3_ids = set()

for value in test_gt["matched_entity_ids"]:
    for entity_id in str(value).split(","):
        entity_id = entity_id.strip()

        if entity_id.startswith("S2-"):
            needed_s2_ids.add(entity_id)
        elif entity_id.startswith("S3-"):
            needed_s3_ids.add(entity_id)

print("Source 2 IDs to find:", len(needed_s2_ids))
print("Source 3 IDs to find:", len(needed_s3_ids))

Source 2 IDs to find: 16
Source 3 IDs to find: 20

In [21]:
def find_records(file_path, needed_ids, chunksize=100_000):
    found = []

    for chunk in pd.read_csv(
        file_path,
        sep="\t",
        dtype=str,
        chunksize=chunksize
    ):
        matches = chunk[chunk["entity_id"].isin(needed_ids)]

        if not matches.empty:
            found.append(matches)

            # Stop if every requested ID has been found
            found_ids = set(
                pd.concat(found)["entity_id"]
            )

            if found_ids >= needed_ids:
                break

    if found:
        return pd.concat(found, ignore_index=True)

    return pd.DataFrame(
        columns=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ]
    )


s2_true_records = find_records(
    base_path + "train_source2.tsv",
    needed_s2_ids
)

s3_true_records = find_records(
    base_path + "train_source3.tsv",
    needed_s3_ids
)

print("Source 2 records found:", len(s2_true_records))
print("Source 3 records found:", len(s3_true_records))

Source 2 records found: 16
Source 3 records found: 20

In [22]:
print("SOURCE 1")
print(
    s1[s1["entity_id"].isin(
        test_gt["source1_entity_id"]
    )][
        ["entity_id", "business_name", "business_address", "country"]
    ].to_string(index=False)
)

print("\nSOURCE 2 — TRUE MATCHES")
print(s2_true_records.to_string(index=False))

print("\nSOURCE 3 — TRUE MATCHES")
print(s3_true_records.to_string(index=False))

SOURCE 1
   entity_id                          business_name                                                                                                                                      business_address country
S1-844896591             Modern Packaging Global PC                                                                                                              8935 Georgetown Pike, Fairfax County, VA      US
S1-539879230                        Novent Owl PLLC                                                                                                                      Des Plaines, IL, 9308 Home Court      US
S1-716830359 Spicer Star Environmental Services LLC                                                                                                              Fl 0, MO, Saint Louis, 9327 Atwood Drive      US
S1-890009542                     SJ Ace Vendome Inc                                                                                                                         60 Uneeda Street, Madison, WV      US
S1-928584878 International Projects (India) Limited #68/3/181, First Floor, Nexsa Royal, 1St Main, Peerless Colony, Kithaganur Main Road, Bhattarahalli, K R Puram, Bangalore South, Bangalore, Karnataka   India
S1-613517393                             Haven Exim                                                                      A/404, Prathna Greens, Sargasan, Gandhinagar, Gandhinagar, Gandhi Nagar, Gujarat   India
S1-832050262                    Shakti Agro Limited                                                                            C/O Gurnav Singh Saluja, Beside Zudio, Kultapara, Sadar, Sambalpur, Orissa   India
S1-201953835              Anderson and Baker Adamas                                                                                                                            12106 Proctor, Houston, TX      US
S1-975588880                               XBL Kpet                                                                                                                         459 Carter Road, Plymouth, CT      US
S1-447656699            Lotus Media Private Limited                                                                      S No.- 160/2 Near Kalika Devi Mandir, Kelwa Palghar, Palghar, Thane, Maharashtra   India

SOURCE 2 — TRUE MATCHES
   entity_id                             business_name                                                                                                                              business_address country
S2-856926544                      ଶକ୍ତି ଆଗ୍ରୋ ଲିମିଟେଡ୍                                                                                                        C/O GURNAV SINGH SALUJA, SADAR, Odisha   India
S2-884418256 Anderson and and Baker Adamas Corporation                                                                                                                   12106  PROCTOR, HOUSTON, TX      US
S2-664447396                            M/s Haven Exim                                                                           A/##404, PRATHNA GREENS, SARGASAN, GANDHINAGAR, GANDHINAGAR, ગુજરાત   India
S2-807723118            Anders0n and Baker Adamas (Co)                                                                                                                   12106  PROCTOR, HOUSTON, TX      US
S2-185735427        International Projects (India) Ltd NO 68/3/181 , FIRST FLOOR, NEXSA ROYAL, 1ST MAIN, PEERLESS COLONY, KITHAGANUR MAIN ROAD, BHATTARAHALLI, K R PURAM, BANGALORE SOUTH, Karnataka   India
 S2-83796020                              Novent [Owl]                                                                                                         9308 Home Court, DES PLAINES CITY, IL      US
S2-348156373              लोटस मीडिया प्राइवेट लिमिटेड                                                    PLOT 401. S NO.- 160/2 NEAR KALIKA DEVI MANDIR, KELWA PALGHAR, PALGHAR, THANE, Maharashtra   India
S2-461344955                          sjacevendome.com                                                                                                                 60 UNEEDA STREET, MADISON, WV      US
S2-649519831                           Haven Exim Exim                                                                           A/##404, PRATHNA GREENS, SARGASAN, GANDHINAGAR, GANDHINAGAR, ગુજરાત   India
S2-306163710        Spicer Star Environmental Services                                                                                                                 MO, SAINT LOUIS, ATWOOD DRIVE      US
S2-932187797                                    #sjace                                                                                                                    UNEEDA STREET, MADISON, WV      US
S2-695716096                                  XBL Kpet                                                                                                                  45 CARTER ROAD, PLYMOUTH, CT      US
S2-795817041        SPICER STAR ENVIRONMENTAL SERVICES                                                                                                                  9327 ATWOOD DR, ST LOUIS, MO      US
S2-362218588                MODERN PACKAGING GLOBAL PC                                                                                                      8935 Georgetown Pike, FAIRFAX COUNTY, VA      US
S2-593664813                             Haven Exim Co                                                                           A/##404, PRATHNA GREENS, SAGRASAN, GANDHINAGAR, GANDHINAGAR, ગુજરાત   India
 S2-84178757                        SJ ACE VENDOME ÍNC                                                                                                                     60 UNEEDA ST, MADISON, WV      US

SOURCE 3 — TRUE MATCHES
   entity_id                           business_name                                                                                                                                    business_address country
 S3-11966366              Modern Packaging Global Pc                                                                                                      8935 Georgetown Pike, Fairfax County, Virginia      US
S3-696813732  Límited International Projects (India) #68/3/181, First Floor, Nexsa Royal, 1St Main, Peerless Colony, Kithaganur Main Road, Bhattarahalli, K R Puram, Bangalore South, Bangalore, ಕರ್ನಾಟಕ   India
S3-839020948 International  (India) Limited Services  68/3/181, First Floor, Nexsa Royal, 1St Main, Peerless Colony, Kithaganur Main Road, Bhattarahalli, K R Puram, Bangalore South, Bangalore, ಕರ್ನಾಟಕ   India
S3-673592452                                  Wexveo                                                                 Block F-264- C/o Gurnav Singh Saluja, Beside Zudio, Kultapara, Sadar, Sambalpur, OD   India
S3-557707615            Anderson and Baker  (Adamas)                                                                                                                       12106 Proctor, Houston, Texas      US
S3-212514545          International Projects (India) #68/3/181, First Floor, Nexsa Royal, 1St Main, Peerless Colony, Kithaganur Main Road, Bhattarahalli, K R Puram, Bangalore South, Bangalore, ಕರ್ನಾಟಕ   India
S3-945806165                  Haven Haven (Services)                                                                                      A/404, Prathna Greens, Sargasan, Gandhinagar, Gandhi Nagar, GJ   India
S3-655306599                         M/s Haven (Edm)                                                                                                                A/404, Gandhinagar, Gandhi Nagar, GJ   India
S3-127246506                         novent owl pllc                                                                                                             9308 Home Ct, DES Plainescity, Illinois      US
S3-737589534      Spicer Star Environmental Services                                                                                                          Stlouis, Missouri, 932 Atwood Drive, Fl. 0      US
S3-117651018           Beloavi d/b/a Novent Owl PLLC                                                                                                                    9308 Home Court, Des Plaines, IL      US
S3-762649005  Spicer-Star Environmental Seraices LLC                                                                                                              932 Atwood Dr, Fl 0, Stlouis, Missouri      US
S3-217931395                     Lotus Media Private                                                                            S No.- 160/2- Near Kalika Devi Mandir, Kelwa Palghar, Palghar, Thane, MH   India
S3-203500929                     SJ Ace Venhdome Inc                                                                                                             West Virginia, 1 Uneeda Street, Madison      US
S3-935370916      International Projects (India) Ltd                     No 68/3/181, First Floor, Nexsa Royal, 1St Main, Peerless Colony, Kithaganur Main Road, Bhattarahalli, K R Puram, Bangalore, KA   India
S3-639477433                            XBL Kpet Ltd                                                                                                          459 Carter Rd, null, Plymouth, Connecticut      US
S3-945547250                         PLLC Novent Ówl                                                                                                             9308 Home Ct, DES Plainescity, Illinois      US
S3-477353991                                XBL Kpet                                                                                                              Carter Rd, null, Plymouth, Connecticut      US
 S3-20727238 International Projects (India)  Limited    No 68/3/181, First Floor, Nexsa Royal, 1St Main, Peerless Colony, Kithaganur Main Road, Bhattarahalli, K R Puram, Bangalore, Bangalore South, KA   India
S3-871697729                                XBL Kpét                                                                                                        459 Carter Road, Connecticut, Plymouth, null      US

In [23]:
import re
import unicodedata
import pandas as pd

LEGAL_WORDS = {
    "private", "limited", "ltd", "pvt",
    "llc", "llp", "inc", "incorporated",
    "corporation", "corp", "company", "co",
    "pllc", "m/s"
}

def normalize_for_blocking(value):
    if pd.isna(value):
        return ""

    value = str(value).lower()

    # Normalize accents: Ówl -> owl
    value = unicodedata.normalize("NFKD", value)
    value = "".join(
        ch for ch in value
        if not unicodedata.combining(ch)
    )

    # Replace punctuation with spaces
    value = re.sub(r"[^\w\s]", " ", value)
    value = re.sub(r"\s+", " ", value).strip()

    return value

def get_name_tokens(value):
    normalized = normalize_for_blocking(value)

    return {
        token
        for token in normalized.split()
        if len(token) >= 3 and token not in LEGAL_WORDS
    }

# Inspect tokenization on our known examples
for name in [
    "Novent Owl PLLC",
    "PLLC Novent Ówl",
    "Haven Exim",
    "M/s Haven Exim",
    "Anderson and Baker Adamas",
]:
    print(name, "->", get_name_tokens(name))

Novent Owl PLLC -> {'owl', 'novent'}
PLLC Novent Ówl -> {'owl', 'novent'}
Haven Exim -> {'haven', 'exim'}
M/s Haven Exim -> {'haven', 'exim'}
Anderson and Baker Adamas -> {'adamas', 'anderson', 'and', 'baker'}

In [24]:
from collections import defaultdict

# Source 1 records from our 10-business test
s1_test = s1[
    s1["entity_id"].isin(test_gt["source1_entity_id"])
].copy()

# Build token sets for the test businesses
s1_test["tokens"] = s1_test["business_name"].apply(
    get_name_tokens
)

# Gather all tokens appearing in the 10 Source 1 names
test_tokens = set()

for tokens in s1_test["tokens"]:
    test_tokens.update(tokens)

print("Source 1 businesses:", len(s1_test))
print("Distinct name tokens:", len(test_tokens))
print(sorted(test_tokens))

Source 1 businesses: 10
Distinct name tokens: 26
['ace', 'adamas', 'agro', 'and', 'anderson', 'baker', 'environmental', 'exim', 'global', 'haven', 'india', 'international', 'kpet', 'lotus', 'media', 'modern', 'novent', 'owl', 'packaging', 'projects', 'services', 'shakti', 'spicer', 'star', 'vendome', 'xbl']

In [25]:
s2_candidate_ids = set(s2_token_candidates["entity_id"])
s3_candidate_ids = set(s3_token_candidates["entity_id"])

found_s2 = needed_s2_ids & s2_candidate_ids
found_s3 = needed_s3_ids & s3_candidate_ids

print("Known Source 2 matches recovered:", len(found_s2), "/", len(needed_s2_ids))
print("Known Source 3 matches recovered:", len(found_s3), "/", len(needed_s3_ids))

NameError: name 's2_token_candidates' is not defined

In [26]:
def retrieve_token_candidates(file_path, test_tokens, chunksize=100_000):
    candidate_records = []

    for chunk in pd.read_csv(
        file_path,
        sep="\t",
        dtype=str,
        chunksize=chunksize
    ):
        chunk["tokens"] = chunk["business_name"].apply(
            get_name_tokens
        )

        mask = chunk["tokens"].apply(
            lambda tokens: bool(tokens & test_tokens)
        )

        if mask.any():
            candidate_records.append(chunk.loc[mask])

    if candidate_records:
        return pd.concat(candidate_records, ignore_index=True)

    return pd.DataFrame()


s2_token_candidates = retrieve_token_candidates(
    base_path + "train_source2.tsv",
    test_tokens
)

print("Source 2 token candidates:", len(s2_token_candidates))

Source 2 token candidates: 538304

In [27]:
s2_candidate_ids = set(s2_token_candidates["entity_id"])
s3_candidate_ids = set(s3_token_candidates["entity_id"])

found_s2 = needed_s2_ids & s2_candidate_ids
found_s3 = needed_s3_ids & s3_candidate_ids

print(
    "Known Source 2 matches recovered:",
    len(found_s2), "/", len(needed_s2_ids)
)
print(
    "Known Source 3 matches recovered:",
    len(found_s3), "/", len(needed_s3_ids)
)

NameError: name 's3_token_candidates' is not defined

In [28]:
s3_token_candidates = retrieve_token_candidates(
    base_path + "train_source3.tsv",
    test_tokens
)

print("Source 3 token candidates:", len(s3_token_candidates))

Source 3 token candidates: 604109

In [29]:
s2_candidate_ids = set(s2_token_candidates["entity_id"])
s3_candidate_ids = set(s3_token_candidates["entity_id"])

found_s2 = needed_s2_ids & s2_candidate_ids
found_s3 = needed_s3_ids & s3_candidate_ids

print("Known Source 2 matches recovered:", len(found_s2), "/", len(needed_s2_ids))
print("Known Source 3 matches recovered:", len(found_s3), "/", len(needed_s3_ids))

Known Source 2 matches recovered: 12 / 16
Known Source 3 matches recovered: 19 / 20

In [30]:
# Known true matches that name-token blocking missed
missed_s2 = needed_s2_ids - s2_candidate_ids
missed_s3 = needed_s3_ids - s3_candidate_ids

print("Missed Source 2 IDs:", missed_s2)
print("Missed Source 3 IDs:", missed_s3)

print("\nMissed Source 2 records:")
print(
    s2_true_records[
        s2_true_records["entity_id"].isin(missed_s2)
    ][["entity_id", "business_name", "business_address", "country"]]
    .to_string(index=False)
)

print("\nMissed Source 3 records:")
print(
    s3_true_records[
        s3_true_records["entity_id"].isin(missed_s3)
    ][["entity_id", "business_name", "business_address", "country"]]
    .to_string(index=False)
)

Missed Source 2 IDs: {'S2-856926544', 'S2-932187797', 'S2-348156373', 'S2-461344955'}
Missed Source 3 IDs: {'S3-673592452'}

Missed Source 2 records:
   entity_id                business_name                                                                           business_address country
S2-856926544         ଶକ୍ତି ଆଗ୍ରୋ ଲିମିଟେଡ୍                                                     C/O GURNAV SINGH SALUJA, SADAR, Odisha   India
S2-348156373 लोटस मीडिया प्राइवेट लिमिटेड PLOT 401. S NO.- 160/2 NEAR KALIKA DEVI MANDIR, KELWA PALGHAR, PALGHAR, THANE, Maharashtra   India
S2-461344955             sjacevendome.com                                                              60 UNEEDA STREET, MADISON, WV      US
S2-932187797                       #sjace                                                                 UNEEDA STREET, MADISON, WV      US

Missed Source 3 records:
   entity_id business_name                                                                    business_address country
S3-673592452        Wexveo Block F-264- C/o Gurnav Singh Saluja, Beside Zudio, Kultapara, Sadar, Sambalpur, OD   India

In [31]:
# Normalize addresses using the same normalization approach
s1_test["address_tokens"] = s1_test["business_address"].apply(
    get_name_tokens
)

s2_true_records["address_tokens"] = (
    s2_true_records["business_address"].apply(get_name_tokens)
)

s3_true_records["address_tokens"] = (
    s3_true_records["business_address"].apply(get_name_tokens)
)

# Show the Source 1 record and its missed true matches
for _, row in test_gt.iterrows():
    s1_id = row["source1_entity_id"]

    source1_row = s1_test[
        s1_test["entity_id"] == s1_id
    ]

    if source1_row.empty:
        continue

    source1_row = source1_row.iloc[0]
    matched_ids = str(row["matched_entity_ids"]).split(",")

    for entity_id in matched_ids:
        entity_id = entity_id.strip()

        if entity_id in missed_s2:
            match_row = s2_true_records[
                s2_true_records["entity_id"] == entity_id
            ]
        elif entity_id in missed_s3:
            match_row = s3_true_records[
                s3_true_records["entity_id"] == entity_id
            ]
        else:
            continue

        if match_row.empty:
            continue

        match_row = match_row.iloc[0]

        overlap = (
            source1_row["address_tokens"]
            & match_row["address_tokens"]
        )

        print("\nSource 1:", source1_row["business_name"])
        print("Source 1 address:", source1_row["business_address"])
        print("Matched record:", match_row["entity_id"])
        print("Matched name:", match_row["business_name"])
        print("Matched address:", match_row["business_address"])
        print("Shared address tokens:", sorted(overlap))

Source 1: Shakti Agro Limited
Source 1 address: C/O Gurnav Singh Saluja, Beside Zudio, Kultapara, Sadar, Sambalpur, Orissa
Matched record: S2-856926544
Matched name: ଶକ୍ତି ଆଗ୍ରୋ ଲିମିଟେଡ୍
Matched address: C/O GURNAV SINGH SALUJA, SADAR, Odisha
Shared address tokens: ['gurnav', 'sadar', 'saluja', 'singh']

Source 1: Shakti Agro Limited
Source 1 address: C/O Gurnav Singh Saluja, Beside Zudio, Kultapara, Sadar, Sambalpur, Orissa
Matched record: S3-673592452
Matched name: Wexveo
Matched address: Block F-264- C/o Gurnav Singh Saluja, Beside Zudio, Kultapara, Sadar, Sambalpur, OD
Shared address tokens: ['beside', 'gurnav', 'kultapara', 'sadar', 'saluja', 'sambalpur', 'singh', 'zudio']

Source 1: Lotus Media Private Limited
Source 1 address: S No.- 160/2 Near Kalika Devi Mandir, Kelwa Palghar, Palghar, Thane, Maharashtra
Matched record: S2-348156373
Matched name: लोटस मीडिया प्राइवेट लिमिटेड
Matched address: PLOT 401. S NO.- 160/2 NEAR KALIKA DEVI MANDIR, KELWA PALGHAR, PALGHAR, THANE, Maharashtra
Shared address tokens: ['160', 'devi', 'kalika', 'kelwa', 'maharashtra', 'mandir', 'near', 'palghar', 'thane']

Source 1: SJ Ace Vendome Inc
Source 1 address: 60 Uneeda Street, Madison, WV
Matched record: S2-932187797
Matched name: #sjace
Matched address: UNEEDA STREET, MADISON, WV
Shared address tokens: ['madison', 'street', 'uneeda']

Source 1: SJ Ace Vendome Inc
Source 1 address: 60 Uneeda Street, Madison, WV
Matched record: S2-461344955
Matched name: sjacevendome.com
Matched address: 60 UNEEDA STREET, MADISON, WV
Shared address tokens: ['madison', 'street', 'uneeda']

In [32]:
from collections import Counter

def token_frequency(series):
    counts = Counter()

    for value in series.dropna():
        counts.update(get_name_tokens(value))

    return counts

s1_address_frequency = token_frequency(s1["business_address"])
s2_address_frequency = token_frequency(s2["business_address"])
s3_address_frequency = token_frequency(s3["business_address"])

print("Most common Source 2 address tokens:")
print(s2_address_frequency.most_common(20))

print("\nMost common Source 3 address tokens:")
print(s3_address_frequency.most_common(20))

Most common Source 2 address tokens:
[('road', 664), ('street', 329), ('floor', 328), ('maharashtra', 312), ('city', 293), ('nagar', 267), ('delhi', 241), ('drive', 230), ('ave', 228), ('new', 207), ('avenue', 202), ('west', 190), ('pradesh', 183), ('plot', 170), ('mumbai', 159), ('null', 134), ('near', 124), ('lane', 120), ('षटर', 119), ('karnataka', 118)]

Most common Source 3 address tokens:
[('road', 578), ('new', 464), ('city', 349), ('street', 335), ('north', 288), ('nagar', 277), ('texas', 264), ('floor', 259), ('delhi', 252), ('drive', 232), ('york', 229), ('carolina', 209), ('avenue', 201), ('ave', 200), ('mumbai', 192), ('west', 185), ('plot', 172), ('unit', 166), ('illinois', 155), ('ohio', 148)]

In [34]:
ADDRESS_STOP_WORDS = {
    "road", "rd", "street", "st", "floor",
    "drive", "dr", "avenue", "ave", "lane",
    "ln", "city", "unit", "suite", "near",
    "plot", "block", "building", "floor",
    "new", "north", "south", "east", "west",
    "and", "the", "for", "of", "in",
    "null", "none", "nan"
}

def get_address_tokens(value):
    tokens = get_name_tokens(value)

    return {
        token for token in tokens
        if token not in ADDRESS_STOP_WORDS
        and not token.isdigit()
    }

In [35]:
s1_test["address_tokens"] = s1_test["business_address"].apply(
    get_address_tokens
)

s1_test[
    ["entity_id", "business_name", "address_tokens"]
]

,entity_id,business_name,address_tokens
731,S1-844896591,Modern Packaging Global PC,"{pike, fairfax, county, georgetown}"
1389,S1-539879230,Novent Owl PLLC,"{court, des, home, plaines}"
1560,S1-716830359,Spicer Star Environmental Services LLC,"{louis, atwood, saint}"
2461,S1-890009542,SJ Ace Vendome Inc,"{uneeda, madison}"
2738,S1-928584878,International Projects (India) Limited,"{bhattarahalli, 1st, first, colony, kithaganur..."
2824,S1-613517393,Haven Exim,"{nagar, prathna, sargasan, gujarat, gandhi, gr..."
3199,S1-832050262,Shakti Agro Limited,"{sambalpur, saluja, kultapara, zudio, beside, ..."
3413,S1-201953835,Anderson and Baker Adamas,"{proctor, houston}"
3477,S1-975588880,XBL Kpet,"{plymouth, carter}"
4708,S1-447656699,Lotus Media Private Limited,"{kalika, devi, thane, kelwa, maharashtra, mand..."

In [36]:
s2_true_records["address_tokens"] = (
    s2_true_records["business_address"].apply(get_address_tokens)
)

s3_true_records["address_tokens"] = (
    s3_true_records["business_address"].apply(get_address_tokens)
)

s1_address_map = s1_test.set_index("entity_id")["address_tokens"]

def address_token_overlap(source1_id, candidate_tokens):
    source_tokens = s1_address_map.get(source1_id, set())
    return source_tokens & candidate_tokens

print("Address-token overlap for known Source 2 matches:")

for _, row in s2_true_records.iterrows():
    overlaps = address_token_overlap(
        row["source1_entity_id"],
        row["address_tokens"]
    )
    print(row["entity_id"], sorted(overlaps))

Address-token overlap for known Source 2 matches:

KeyError: 'source1_entity_id'

In [37]:
print("Source 2 true matches:")
print(s2_true_records.columns.tolist())

print("\nSource 3 true matches:")
print(s3_true_records.columns.tolist())

print("\nGround truth:")
print(test_gt.columns.tolist())

Source 2 true matches:
['entity_id', 'business_name', 'business_address', 'country', 'address_tokens']

Source 3 true matches:
['entity_id', 'business_name', 'business_address', 'country', 'address_tokens']

Ground truth:
['source1_entity_id', 'matched_entity_ids']

In [38]:
# Create a mapping from each true matched ID to its Source 1 ID
true_match_map = {}

for _, row in test_gt.iterrows():
    s1_id = row["source1_entity_id"]
    matched_ids = row["matched_entity_ids"]

    if pd.isna(matched_ids):
        continue

    for match_id in str(matched_ids).split(","):
        match_id = match_id.strip()
        if match_id:
            true_match_map[match_id] = s1_id

# Add the corresponding Source 1 ID to each true-match record
s2_true_records["source1_entity_id"] = (
    s2_true_records["entity_id"].map(true_match_map)
)

s3_true_records["source1_entity_id"] = (
    s3_true_records["entity_id"].map(true_match_map)
)

print("Source 2 records linked:", 
      s2_true_records["source1_entity_id"].notna().sum())

print("Source 3 records linked:", 
      s3_true_records["source1_entity_id"].notna().sum())

Source 2 records linked: 16
Source 3 records linked: 20

In [39]:
s1_address_map = s1_test.set_index("entity_id")["address_tokens"]

def address_token_overlap(source1_id, candidate_tokens):
    source_tokens = s1_address_map.get(source1_id, set())
    return source_tokens & candidate_tokens

print("SOURCE 2 TRUE MATCHES")

for _, row in s2_true_records.iterrows():
    overlap = address_token_overlap(
        row["source1_entity_id"],
        row["address_tokens"]
    )
    print(row["entity_id"], "->", sorted(overlap))

print("\nSOURCE 3 TRUE MATCHES")

for _, row in s3_true_records.iterrows():
    overlap = address_token_overlap(
        row["source1_entity_id"],
        row["address_tokens"]
    )
    print(row["entity_id"], "->", sorted(overlap))

SOURCE 2 TRUE MATCHES
S2-856926544 -> ['gurnav', 'sadar', 'saluja', 'singh']
S2-884418256 -> ['houston', 'proctor']
S2-664447396 -> ['gandhinagar', 'greens', 'prathna', 'sargasan']
S2-807723118 -> ['houston', 'proctor']
S2-185735427 -> ['1st', 'bangalore', 'bhattarahalli', 'colony', 'first', 'karnataka', 'kithaganur', 'main', 'nexsa', 'peerless', 'puram', 'royal']
S2-83796020 -> ['court', 'des', 'home', 'plaines']
S2-348156373 -> ['devi', 'kalika', 'kelwa', 'maharashtra', 'mandir', 'palghar', 'thane']
S2-461344955 -> ['madison', 'uneeda']
S2-649519831 -> ['gandhinagar', 'greens', 'prathna', 'sargasan']
S2-306163710 -> ['atwood', 'louis', 'saint']
S2-932187797 -> ['madison', 'uneeda']
S2-695716096 -> ['carter', 'plymouth']
S2-795817041 -> ['atwood', 'louis']
S2-362218588 -> ['county', 'fairfax', 'georgetown', 'pike']
S2-593664813 -> ['gandhinagar', 'greens', 'prathna']
S2-84178757 -> ['madison', 'uneeda']

SOURCE 3 TRUE MATCHES
S3-11966366 -> ['county', 'fairfax', 'georgetown', 'pike']
S3-696813732 -> ['1st', 'bangalore', 'bhattarahalli', 'colony', 'first', 'kithaganur', 'main', 'nexsa', 'peerless', 'puram', 'royal']
S3-839020948 -> ['1st', 'bangalore', 'bhattarahalli', 'colony', 'first', 'kithaganur', 'main', 'nexsa', 'peerless', 'puram', 'royal']
S3-673592452 -> ['beside', 'gurnav', 'kultapara', 'sadar', 'saluja', 'sambalpur', 'singh', 'zudio']
S3-557707615 -> ['houston', 'proctor']
S3-212514545 -> ['1st', 'bangalore', 'bhattarahalli', 'colony', 'first', 'kithaganur', 'main', 'nexsa', 'peerless', 'puram', 'royal']
S3-945806165 -> ['gandhi', 'gandhinagar', 'greens', 'nagar', 'prathna', 'sargasan']
S3-655306599 -> ['gandhi', 'gandhinagar', 'nagar']
S3-127246506 -> ['des', 'home']
S3-737589534 -> ['atwood']
S3-117651018 -> ['court', 'des', 'home', 'plaines']
S3-762649005 -> ['atwood']
S3-217931395 -> ['devi', 'kalika', 'kelwa', 'mandir', 'palghar', 'thane']
S3-203500929 -> ['madison', 'uneeda']
S3-935370916 -> ['1st', 'bangalore', 'bhattarahalli', 'colony', 'first', 'kithaganur', 'main', 'nexsa', 'peerless', 'puram', 'royal']
S3-639477433 -> ['carter', 'plymouth']
S3-945547250 -> ['des', 'home']
S3-477353991 -> ['carter', 'plymouth']
S3-20727238 -> ['1st', 'bangalore', 'bhattarahalli', 'colony', 'first', 'kithaganur', 'main', 'nexsa', 'peerless', 'puram', 'royal']
S3-871697729 -> ['carter', 'plymouth']

In [40]:
from pathlib import Path

project_path = Path(
    "/Users/aiwinthomas/Downloads/Business Entity Resolution"
)

for folder in ["dataset/train", "dataset/test"]:
    print(f"\n{folder}:")
    for file in sorted((project_path / folder).glob("*.tsv")):
        print(file.name, f"{file.stat().st_size / (1024**3):.2f} GB")

dataset/train:
train_ground_truth.tsv 0.12 GB
train_source1.tsv 0.20 GB
train_source2.tsv 0.46 GB
train_source3.tsv 0.47 GB

dataset/test:
test_source1.tsv 0.16 GB
test_source2.tsv 0.47 GB
test_source3.tsv 0.47 GB

In [41]:
import pandas as pd

test_path = project_path / "dataset" / "test"

for source in ["source1", "source2", "source3"]:
    file_path = test_path / f"test_{source}.tsv"

    sample = pd.read_csv(
        file_path,
        sep="\t",
        nrows=5,
        dtype=str
    )

    print(f"\n{source.upper()}")
    print("Columns:", sample.columns.tolist())
    print(sample.head(2).to_string(index=False))

SOURCE1
Columns: ['entity_id', 'business_name', 'business_address', 'country']
   entity_id        business_name                       business_address country
S1-714132312      Zephay Labs Inc            2621 Cotten Road, Tyler, TX      US
S1-106407869 Vision Partners Corp IA, Iowa City, 1064 Newton Rd, Unit 11      US

SOURCE2
Columns: ['entity_id', 'business_name', 'business_address', 'country']
   entity_id            business_name                                   business_address country
S2-192345572          Brahma Infosoft COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karnataka   India
S2-566025912 Marina Ecole France Sarl            63 R. DE DIEPPE, LILLE, Hauts-de-France  France

SOURCE3
Columns: ['entity_id', 'business_name', 'business_address', 'country']
   entity_id         business_name                                                     business_address country
S3-462677478        मॉडर्न फाइनेंस No 10 Enkay Square, 448A, Udyog Vihar Phase V, Gurugram, Gurgaon, HR   India
S3-374810425 Shri Sai Infratech Co                                                3/115, East Delhi, DL   India

In [42]:
import os
import psutil

memory = psutil.virtual_memory()

print(f"Total RAM: {memory.total / (1024**3):.1f} GB")
print(f"Available RAM: {memory.available / (1024**3):.1f} GB")
print(f"CPU cores: {os.cpu_count()}")

Total RAM: 8.0 GB
Available RAM: 1.7 GB
CPU cores: 8

In [43]:
import shutil

disk = shutil.disk_usage(project_path)

print(f"Free disk space: {disk.free / (1024**3):.2f} GB")
print(f"Total disk space: {disk.total / (1024**3):.2f} GB")

output_path = project_path / "output"
output_path.mkdir(exist_ok=True)

print("Output folder ready:", output_path)

Free disk space: 147.74 GB
Total disk space: 228.27 GB
Output folder ready: /Users/aiwinthomas/Downloads/Business Entity Resolution/output